apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: oh89mfjaf-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-56d258bbe0.su0l.p3.openshiftapps.com/rhtap/rhtap-qe-java-springboot:8d1ddc014d5053c34938f5059296c1d0db5102a6@sha256:951c0ce38e6125b66066096162395a8c55655c6bf2ce727303a943103f82fe15
          name: container-image
